version: "3"
services:
  web:
    image: ilungj/pipe
    ports:
      - "80:3000"

  db:
    image: ilungj/hacc-db
    volumes:
      - /data/db:/data/db
      - /data/dump:/data/dump
    ports:
      - 27017:27017