version: "3"
services:
  web:
    build: ./web
    container_name: "web"
    volumes:
      - ./web:/web
    ports:
      - "3000:3000"

  db:
    image: ilungj/hacc-db
    container_name: "database"
    volumes:
      - ./sample_data/data/db:/data/db
    ports:
      - 27017:27017